[profile.default]
solc_version = "0.8.13"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
src = "src"
test = "test"
out = "out"
allow_paths = ["../../node_modules", "../../../../packages"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"
[profile.astar-testnet]
eth_rpc_url = "https://shibuya.public.blastapi.io"
[profile.mumbai]
eth_rpc_url = "https://polygon-mumbai.g.alchemy.com/v2/cZIYtiVMNzwFuZYuNOoatDnt8y7FN8ox"
# eth_rpc_url = "${MUMBAI_API_KEY}"
[profile.fuji]
eth_rpc_url = "https://api.avax-test.network/ext/bc/C/rpc"
[profile.local]
eth_rpc_url = "127.0.0.1:8545"
[profile.intmax]
eth_rpc_url = "https://prealpha.testnet.intmax.io/"
[profile.opgoerli]
eth_rpc_url = "https://goerli.optimism.io"
[profile.arbgoerli]
eth_rpc_url = "https://goerli-rollup.arbitrum.io/rpc"